<?php
/**
 * Starting5x5 — times titulares históricos, curados à mão.
 *
 * Base própria do jogo, sem depender de hoopgrid_players/build_notas: cada
 * "time" aqui é a escalação titular real de uma temporada específica (não o
 * elenco inteiro), com posição(ões) e OVR por jogador. Vários jogadores têm
 * mais de uma posição elegível de propósito — é o que dá profundidade pra
 * escolha na hora de montar o próprio time (ver dreamteam.php).
 *
 * Escala de OVR livre (não é a mesma do Build-A-Player) — vai de ~73 (papel
 * coadjuvante real) até 99 (o pico de carreira de quem definiu a época).
 */
function dtTimesHistoricos(): array
{
    return [
        ['id' => 'bulls96', 'nome' => 'Bulls 1995-96', 'ano' => 1996, 'jogadores' => [
            ['nome' => 'Jordan',       'pos' => ['SG', 'SF'], 'ovr' => 99],
            ['nome' => 'Harper',       'pos' => ['PG', 'SG'], 'ovr' => 82],
            ['nome' => 'Pippen',       'pos' => ['SF', 'PF'], 'ovr' => 95],
            ['nome' => 'Rodman',       'pos' => ['PF', 'C'],  'ovr' => 88],
            ['nome' => 'Longley',      'pos' => ['C'],        'ovr' => 76],
        ]],
        ['id' => 'bulls97', 'nome' => 'Bulls 1996-97', 'ano' => 1997, 'jogadores' => [
            ['nome' => 'Jordan',       'pos' => ['SG', 'SF'], 'ovr' => 98],
            ['nome' => 'Harper',       'pos' => ['PG', 'SG'], 'ovr' => 81],
            ['nome' => 'Pippen',       'pos' => ['SF', 'PF'], 'ovr' => 94],
            ['nome' => 'Rodman',       'pos' => ['PF', 'C'],  'ovr' => 87],
            ['nome' => 'Longley',      'pos' => ['C'],        'ovr' => 76],
        ]],
        ['id' => 'lakers87', 'nome' => 'Lakers 1986-87', 'ano' => 1987, 'jogadores' => [
            ['nome' => 'Magic',        'pos' => ['PG'],       'ovr' => 97],
            ['nome' => 'Byron Scott',  'pos' => ['SG'],       'ovr' => 85],
            ['nome' => 'Worthy',       'pos' => ['SF', 'PF'], 'ovr' => 91],
            ['nome' => 'A.C. Green',   'pos' => ['PF'],       'ovr' => 80],
            ['nome' => 'Kareem',       'pos' => ['C'],        'ovr' => 91],
        ]],
        ['id' => 'celtics86', 'nome' => 'Celtics 1985-86', 'ano' => 1986, 'jogadores' => [
            ['nome' => 'D. Johnson',   'pos' => ['PG', 'SG'], 'ovr' => 88],
            ['nome' => 'Ainge',        'pos' => ['SG', 'PG'], 'ovr' => 82],
            ['nome' => 'Bird',         'pos' => ['SF', 'PF'], 'ovr' => 98],
            ['nome' => 'McHale',       'pos' => ['PF', 'C'],  'ovr' => 94],
            ['nome' => 'Parish',       'pos' => ['C'],        'ovr' => 89],
        ]],
        ['id' => 'warriors17', 'nome' => 'Warriors 2016-17', 'ano' => 2017, 'jogadores' => [
            ['nome' => 'Curry',        'pos' => ['PG'],       'ovr' => 97],
            ['nome' => 'Klay',         'pos' => ['SG'],       'ovr' => 90],
            ['nome' => 'Durant',       'pos' => ['SF', 'PF'], 'ovr' => 98],
            ['nome' => 'Draymond',     'pos' => ['PF', 'C'],  'ovr' => 89],
            ['nome' => 'Pachulia',     'pos' => ['C'],        'ovr' => 74],
        ]],
        ['id' => 'warriors18', 'nome' => 'Warriors 2017-18', 'ano' => 2018, 'jogadores' => [
            ['nome' => 'Curry',        'pos' => ['PG'],       'ovr' => 97],
            ['nome' => 'Klay',         'pos' => ['SG'],       'ovr' => 89],
            ['nome' => 'Durant',       'pos' => ['SF', 'PF'], 'ovr' => 98],
            ['nome' => 'Draymond',     'pos' => ['PF', 'C'],  'ovr' => 88],
            ['nome' => 'Pachulia',     'pos' => ['C'],        'ovr' => 73],
        ]],
        ['id' => 'lakers82', 'nome' => 'Lakers 1981-82', 'ano' => 1982, 'jogadores' => [
            ['nome' => 'Magic',         'pos' => ['PG'],       'ovr' => 91],
            ['nome' => 'Nixon',         'pos' => ['PG', 'SG'], 'ovr' => 83],
            ['nome' => 'Wilkes',        'pos' => ['SF', 'PF'], 'ovr' => 85],
            ['nome' => 'McAdoo',        'pos' => ['PF', 'C'],  'ovr' => 84],
            ['nome' => 'Kareem',        'pos' => ['C'],        'ovr' => 92],
        ]],
        ['id' => 'sixers83', 'nome' => '76ers 1982-83', 'ano' => 1983, 'jogadores' => [
            ['nome' => 'Cheeks',       'pos' => ['PG'],       'ovr' => 85],
            ['nome' => 'Toney',        'pos' => ['SG'],       'ovr' => 87],
            ['nome' => 'Erving',       'pos' => ['SF', 'PF'], 'ovr' => 94],
            ['nome' => 'B. Jones',     'pos' => ['PF', 'SF'], 'ovr' => 84],
            ['nome' => 'Malone',       'pos' => ['C'],        'ovr' => 93],
        ]],
        ['id' => 'lakers01', 'nome' => 'Lakers 2000-01', 'ano' => 2001, 'jogadores' => [
            ['nome' => 'Kobe',         'pos' => ['SG', 'SF'], 'ovr' => 93],
            ['nome' => 'Fisher',       'pos' => ['PG'],       'ovr' => 78],
            ['nome' => 'Fox',          'pos' => ['SF'],       'ovr' => 79],
            ['nome' => 'Horry',        'pos' => ['PF', 'SF'], 'ovr' => 80],
            ['nome' => 'Shaq',         'pos' => ['C'],        'ovr' => 99],
        ]],
        ['id' => 'bulls92', 'nome' => 'Bulls 1991-92', 'ano' => 1992, 'jogadores' => [
            ['nome' => 'Jordan',       'pos' => ['SG', 'SF'], 'ovr' => 98],
            ['nome' => 'Paxson',       'pos' => ['PG', 'SG'], 'ovr' => 77],
            ['nome' => 'Pippen',       'pos' => ['SF', 'PF'], 'ovr' => 92],
            ['nome' => 'Grant',        'pos' => ['PF'],       'ovr' => 85],
            ['nome' => 'Cartwright',   'pos' => ['C'],        'ovr' => 78],
        ]],
        ['id' => 'pistons89', 'nome' => 'Pistons 1988-89', 'ano' => 1989, 'jogadores' => [
            ['nome' => 'Isiah',        'pos' => ['PG'],       'ovr' => 91],
            ['nome' => 'Dumars',       'pos' => ['SG', 'PG'], 'ovr' => 86],
            ['nome' => 'Aguirre',      'pos' => ['SF', 'PF'], 'ovr' => 84],
            ['nome' => 'Rodman',       'pos' => ['PF'],       'ovr' => 82],
            ['nome' => 'Laimbeer',     'pos' => ['C', 'PF'],  'ovr' => 85],
        ]],
        ['id' => 'pistons90', 'nome' => 'Pistons 1989-90', 'ano' => 1990, 'jogadores' => [
            ['nome' => 'Isiah',        'pos' => ['PG'],       'ovr' => 91],
            ['nome' => 'Dumars',       'pos' => ['SG', 'PG'], 'ovr' => 87],
            ['nome' => 'Aguirre',      'pos' => ['SF', 'PF'], 'ovr' => 82],
            ['nome' => 'Rodman',       'pos' => ['PF'],       'ovr' => 84],
            ['nome' => 'Laimbeer',     'pos' => ['C', 'PF'],  'ovr' => 84],
        ]],
        ['id' => 'knicks70', 'nome' => 'Knicks 1969-70', 'ano' => 1970, 'jogadores' => [
            ['nome' => 'Frazier',       'pos' => ['PG', 'SG'], 'ovr' => 91],
            ['nome' => 'Barnett',       'pos' => ['SG'],       'ovr' => 82],
            ['nome' => 'Bradley',       'pos' => ['SF'],       'ovr' => 82],
            ['nome' => 'DeBusschere',   'pos' => ['PF'],       'ovr' => 88],
            ['nome' => 'Reed',          'pos' => ['C', 'PF'],  'ovr' => 90],
        ]],
        ['id' => 'knicks73', 'nome' => 'Knicks 1972-73', 'ano' => 1973, 'jogadores' => [
            ['nome' => 'Frazier',       'pos' => ['PG', 'SG'], 'ovr' => 93],
            ['nome' => 'Monroe',        'pos' => ['SG', 'PG'], 'ovr' => 88],
            ['nome' => 'Bradley',       'pos' => ['SF'],       'ovr' => 83],
            ['nome' => 'DeBusschere',   'pos' => ['PF'],       'ovr' => 87],
            ['nome' => 'Reed',          'pos' => ['C', 'PF'],  'ovr' => 88],
        ]],
        ['id' => 'sixers67', 'nome' => '76ers 1966-67', 'ano' => 1967, 'jogadores' => [
            ['nome' => 'Greer',         'pos' => ['SG', 'PG'], 'ovr' => 88],
            ['nome' => 'Jones',         'pos' => ['SG'],       'ovr' => 78],
            ['nome' => 'Walker',        'pos' => ['SF', 'PF'], 'ovr' => 85],
            ['nome' => 'Jackson',       'pos' => ['PF', 'C'],  'ovr' => 79],
            ['nome' => 'Chamberlain',   'pos' => ['C'],        'ovr' => 98],
        ]],
        ['id' => 'celtics65', 'nome' => 'Celtics 1964-65', 'ano' => 1965, 'jogadores' => [
            ['nome' => 'K.C. Jones',    'pos' => ['PG'],       'ovr' => 80],
            ['nome' => 'Sam Jones',     'pos' => ['SG'],       'ovr' => 87],
            ['nome' => 'Havlicek',      'pos' => ['SF', 'SG'], 'ovr' => 89],
            ['nome' => 'Heinsohn',      'pos' => ['PF', 'SF'], 'ovr' => 83],
            ['nome' => 'Russell',       'pos' => ['C'],        'ovr' => 96],
        ]],
        ['id' => 'heat13', 'nome' => 'Heat 2012-13', 'ano' => 2013, 'jogadores' => [
            ['nome' => 'Chalmers',     'pos' => ['PG'],       'ovr' => 78],
            ['nome' => 'Wade',         'pos' => ['SG', 'PG'], 'ovr' => 91],
            ['nome' => 'LeBron',       'pos' => ['SF', 'PF'], 'ovr' => 98],
            ['nome' => 'Battier',      'pos' => ['SF', 'PF'], 'ovr' => 78],
            ['nome' => 'Bosh',         'pos' => ['PF', 'C'],  'ovr' => 86],
        ]],
        ['id' => 'spurs14', 'nome' => 'Spurs 2013-14', 'ano' => 2014, 'jogadores' => [
            ['nome' => 'Parker',       'pos' => ['PG'],       'ovr' => 89],
            ['nome' => 'Green',        'pos' => ['SG'],       'ovr' => 80],
            ['nome' => 'Kawhi',        'pos' => ['SF'],       'ovr' => 89],
            ['nome' => 'Diaw',         'pos' => ['PF', 'SF'], 'ovr' => 79],
            ['nome' => 'Duncan',       'pos' => ['C', 'PF'],  'ovr' => 90],
        ]],
        ['id' => 'lakers09', 'nome' => 'Lakers 2008-09', 'ano' => 2009, 'jogadores' => [
            ['nome' => 'Fisher',       'pos' => ['PG'],       'ovr' => 78],
            ['nome' => 'Kobe',         'pos' => ['SG', 'SF'], 'ovr' => 96],
            ['nome' => 'Ariza',        'pos' => ['SF', 'SG'], 'ovr' => 78],
            ['nome' => 'Gasol',        'pos' => ['PF', 'C'],  'ovr' => 90],
            ['nome' => 'Bynum',        'pos' => ['C'],        'ovr' => 82],
        ]],
        ['id' => 'lakers10', 'nome' => 'Lakers 2009-10', 'ano' => 2010, 'jogadores' => [
            ['nome' => 'Fisher',       'pos' => ['PG'],       'ovr' => 77],
            ['nome' => 'Kobe',         'pos' => ['SG', 'SF'], 'ovr' => 96],
            ['nome' => 'Artest',       'pos' => ['SF', 'SG'], 'ovr' => 80],
            ['nome' => 'Gasol',        'pos' => ['PF', 'C'],  'ovr' => 91],
            ['nome' => 'Odom',         'pos' => ['PF', 'C'],  'ovr' => 84],
        ]],
        ['id' => 'lakers80', 'nome' => 'Lakers 1979-80', 'ano' => 1980, 'jogadores' => [
            ['nome' => 'Magic',        'pos' => ['PG'],       'ovr' => 90],
            ['nome' => 'Nixon',        'pos' => ['PG', 'SG'], 'ovr' => 82],
            ['nome' => 'Wilkes',       'pos' => ['SF', 'PF'], 'ovr' => 84],
            ['nome' => 'Chones',       'pos' => ['PF', 'C'],  'ovr' => 78],
            ['nome' => 'Kareem',       'pos' => ['C'],        'ovr' => 96],
        ]],
        ['id' => 'celtics84', 'nome' => 'Celtics 1983-84', 'ano' => 1984, 'jogadores' => [
            ['nome' => 'D. Johnson',   'pos' => ['PG', 'SG'], 'ovr' => 89],
            ['nome' => 'Ainge',        'pos' => ['SG', 'PG'], 'ovr' => 82],
            ['nome' => 'Bird',         'pos' => ['SF', 'PF'], 'ovr' => 97],
            ['nome' => 'Maxwell',      'pos' => ['PF', 'SF'], 'ovr' => 82],
            ['nome' => 'Parish',       'pos' => ['C'],        'ovr' => 90],
        ]],
        ['id' => 'warriors19', 'nome' => 'Warriors 2018-19', 'ano' => 2019, 'jogadores' => [
            ['nome' => 'Curry',        'pos' => ['PG'],       'ovr' => 97],
            ['nome' => 'Klay',         'pos' => ['SG'],       'ovr' => 88],
            ['nome' => 'Durant',       'pos' => ['SF', 'PF'], 'ovr' => 97],
            ['nome' => 'Draymond',     'pos' => ['PF', 'C'],  'ovr' => 87],
            ['nome' => 'Cousins',      'pos' => ['C'],        'ovr' => 82],
        ]],
        ['id' => 'warriors76', 'nome' => 'Warriors 1975-76', 'ano' => 1976, 'jogadores' => [
            ['nome' => 'Beard',        'pos' => ['PG', 'SG'], 'ovr' => 79],
            ['nome' => 'C. Johnson',   'pos' => ['SG'],       'ovr' => 77],
            ['nome' => 'Wilkes',       'pos' => ['SF', 'PF'], 'ovr' => 82],
            ['nome' => 'Barry',        'pos' => ['SF', 'PF'], 'ovr' => 92],
            ['nome' => 'Ray',          'pos' => ['C', 'PF'],  'ovr' => 81],
        ]],
        ['id' => 'bullets78', 'nome' => 'Bullets 1977-78', 'ano' => 1978, 'jogadores' => [
            ['nome' => 'Grevey',       'pos' => ['SG'],       'ovr' => 80],
            ['nome' => 'Henderson',    'pos' => ['PG'],       'ovr' => 77],
            ['nome' => 'Dandridge',    'pos' => ['SF', 'PF'], 'ovr' => 86],
            ['nome' => 'Hayes',        'pos' => ['PF', 'C'],  'ovr' => 88],
            ['nome' => 'Unseld',       'pos' => ['C', 'PF'],  'ovr' => 87],
        ]],
        ['id' => 'rockets94', 'nome' => 'Rockets 1993-94', 'ano' => 1994, 'jogadores' => [
            ['nome' => 'K. Smith',     'pos' => ['PG'],       'ovr' => 79],
            ['nome' => 'Maxwell',      'pos' => ['SG', 'PG'], 'ovr' => 78],
            ['nome' => 'Horry',        'pos' => ['SF', 'PF'], 'ovr' => 81],
            ['nome' => 'Thorpe',       'pos' => ['PF'],       'ovr' => 82],
            ['nome' => 'Olajuwon',     'pos' => ['C'],        'ovr' => 97],
        ]],
        ['id' => 'rockets95', 'nome' => 'Rockets 1994-95', 'ano' => 1995, 'jogadores' => [
            ['nome' => 'K. Smith',     'pos' => ['PG'],       'ovr' => 78],
            ['nome' => 'Drexler',      'pos' => ['SG', 'SF'], 'ovr' => 90],
            ['nome' => 'Horry',        'pos' => ['SF', 'PF'], 'ovr' => 82],
            ['nome' => 'Thorpe',       'pos' => ['PF'],       'ovr' => 81],
            ['nome' => 'Olajuwon',     'pos' => ['C'],        'ovr' => 97],
        ]],
        ['id' => 'pistons04', 'nome' => 'Pistons 2003-04', 'ano' => 2004, 'jogadores' => [
            ['nome' => 'Billups',      'pos' => ['PG'],       'ovr' => 84],
            ['nome' => 'R. Hamilton',  'pos' => ['SG'],       'ovr' => 85],
            ['nome' => 'Prince',       'pos' => ['SF', 'PF'], 'ovr' => 80],
            ['nome' => 'R. Wallace',   'pos' => ['PF', 'C'],  'ovr' => 87],
            ['nome' => 'B. Wallace',   'pos' => ['C', 'PF'],  'ovr' => 87],
        ]],
        ['id' => 'bulls98', 'nome' => 'Bulls 1997-98', 'ano' => 1998, 'jogadores' => [
            ['nome' => 'Jordan',       'pos' => ['SG', 'SF'], 'ovr' => 97],
            ['nome' => 'Harper',       'pos' => ['PG', 'SG'], 'ovr' => 78],
            ['nome' => 'Pippen',       'pos' => ['SF', 'PF'], 'ovr' => 92],
            ['nome' => 'Rodman',       'pos' => ['PF', 'C'],  'ovr' => 84],
            ['nome' => 'Longley',      'pos' => ['C'],        'ovr' => 75],
        ]],
        ['id' => 'cavs16', 'nome' => 'Cavaliers 2015-16', 'ano' => 2016, 'jogadores' => [
            ['nome' => 'Kyrie',        'pos' => ['PG', 'SG'], 'ovr' => 89],
            ['nome' => 'J.R. Smith',   'pos' => ['SG', 'SF'], 'ovr' => 79],
            ['nome' => 'LeBron',       'pos' => ['SF', 'PF'], 'ovr' => 96],
            ['nome' => 'Love',         'pos' => ['PF', 'C'],  'ovr' => 87],
            ['nome' => 'T. Thompson',  'pos' => ['C', 'PF'],  'ovr' => 78],
        ]],
        ['id' => 'celtics62', 'nome' => 'Celtics 1961-62', 'ano' => 1962, 'jogadores' => [
            ['nome' => 'Cousy',         'pos' => ['PG'],       'ovr' => 88],
            ['nome' => 'Sam Jones',     'pos' => ['SG'],       'ovr' => 84],
            ['nome' => 'Havlicek',      'pos' => ['SF', 'SG'], 'ovr' => 82],
            ['nome' => 'Heinsohn',      'pos' => ['PF', 'SF'], 'ovr' => 85],
            ['nome' => 'Russell',       'pos' => ['C'],        'ovr' => 95],
        ]],
        ['id' => 'celtics69', 'nome' => 'Celtics 1968-69', 'ano' => 1969, 'jogadores' => [
            ['nome' => 'Sam Jones',     'pos' => ['SG', 'PG'], 'ovr' => 83],
            ['nome' => 'Bailey Howell', 'pos' => ['SF', 'PF'], 'ovr' => 82],
            ['nome' => 'Havlicek',      'pos' => ['SF', 'SG'], 'ovr' => 90],
            ['nome' => 'Nelson',        'pos' => ['PF'],       'ovr' => 79],
            ['nome' => 'Russell',       'pos' => ['C'],        'ovr' => 90],
        ]],
        ['id' => 'lakers88', 'nome' => 'Lakers 1987-88', 'ano' => 1988, 'jogadores' => [
            ['nome' => 'Magic',         'pos' => ['PG'],       'ovr' => 96],
            ['nome' => 'Byron Scott',   'pos' => ['SG'],       'ovr' => 85],
            ['nome' => 'Worthy',        'pos' => ['SF', 'PF'], 'ovr' => 90],
            ['nome' => 'A.C. Green',    'pos' => ['PF'],       'ovr' => 81],
            ['nome' => 'Kareem',        'pos' => ['C'],        'ovr' => 87],
        ]],
        ['id' => 'bucks71', 'nome' => 'Bucks 1970-71', 'ano' => 1971, 'jogadores' => [
            ['nome' => 'Oscar Robertson', 'pos' => ['PG'],     'ovr' => 91],
            ['nome' => 'Jon McGlocklin',  'pos' => ['SG'],     'ovr' => 79],
            ['nome' => 'Bobby Dandridge', 'pos' => ['SF', 'PF'], 'ovr' => 84],
            ['nome' => 'Greg Smith',      'pos' => ['PF'],     'ovr' => 76],
            ['nome' => 'Kareem',          'pos' => ['C'],      'ovr' => 96],
        ]],
        ['id' => 'bucks21', 'nome' => 'Bucks 2020-21', 'ano' => 2021, 'jogadores' => [
            ['nome' => 'Jrue Holiday',  'pos' => ['PG', 'SG'], 'ovr' => 87],
            ['nome' => 'Bryn Forbes',   'pos' => ['SG'],       'ovr' => 74],
            ['nome' => 'Middleton',     'pos' => ['SF', 'SG'], 'ovr' => 88],
            ['nome' => 'Giannis',       'pos' => ['PF', 'C'],  'ovr' => 96],
            ['nome' => 'Brook Lopez',   'pos' => ['C'],        'ovr' => 82],
        ]],
        ['id' => 'bucks22', 'nome' => 'Bucks 2021-22', 'ano' => 2022, 'jogadores' => [
            ['nome' => 'Jrue Holiday',  'pos' => ['PG', 'SG'], 'ovr' => 87],
            ['nome' => 'Grayson Allen', 'pos' => ['SG'],       'ovr' => 78],
            ['nome' => 'Middleton',     'pos' => ['SF', 'SG'], 'ovr' => 87],
            ['nome' => 'Giannis',       'pos' => ['PF', 'C'],  'ovr' => 97],
            ['nome' => 'Brook Lopez',   'pos' => ['C'],        'ovr' => 83],
        ]],
        ['id' => 'nuggets23', 'nome' => 'Nuggets 2022-23', 'ano' => 2023, 'jogadores' => [
            ['nome' => 'Jamal Murray',  'pos' => ['PG'],       'ovr' => 87],
            ['nome' => 'Caldwell-Pope', 'pos' => ['SG'],       'ovr' => 80],
            ['nome' => 'Porter Jr.',    'pos' => ['SF', 'PF'], 'ovr' => 82],
            ['nome' => 'Aaron Gordon',  'pos' => ['PF', 'SF'], 'ovr' => 83],
            ['nome' => 'Jokic',         'pos' => ['C'],        'ovr' => 98],
        ]],
        ['id' => 'raptors19', 'nome' => 'Raptors 2018-19', 'ano' => 2019, 'jogadores' => [
            ['nome' => 'Kyle Lowry',    'pos' => ['PG'],       'ovr' => 86],
            ['nome' => 'Danny Green',   'pos' => ['SG'],       'ovr' => 79],
            ['nome' => 'Kawhi',         'pos' => ['SF', 'PF'], 'ovr' => 96],
            ['nome' => 'Siakam',        'pos' => ['PF'],       'ovr' => 84],
            ['nome' => 'Marc Gasol',    'pos' => ['C'],        'ovr' => 83],
        ]],
        ['id' => 'mavs11', 'nome' => 'Mavericks 2010-11', 'ano' => 2011, 'jogadores' => [
            ['nome' => 'Jason Kidd',    'pos' => ['PG'],       'ovr' => 84],
            ['nome' => 'Stevenson',     'pos' => ['SG'],       'ovr' => 72],
            ['nome' => 'Shawn Marion',  'pos' => ['SF', 'PF'], 'ovr' => 82],
            ['nome' => 'Dirk',          'pos' => ['PF', 'C'],  'ovr' => 95],
            ['nome' => 'Tyson Chandler','pos' => ['C'],        'ovr' => 82],
        ]],
        ['id' => 'spurs03', 'nome' => 'Spurs 2002-03', 'ano' => 2003, 'jogadores' => [
            ['nome' => 'Tony Parker',   'pos' => ['PG'],       'ovr' => 80],
            ['nome' => 'S. Jackson',    'pos' => ['SG', 'SF'], 'ovr' => 78],
            ['nome' => 'Bruce Bowen',   'pos' => ['SF'],       'ovr' => 76],
            ['nome' => 'Duncan',        'pos' => ['PF', 'C'],  'ovr' => 96],
            ['nome' => 'David Robinson','pos' => ['C'],        'ovr' => 84],
        ]],
        ['id' => 'spurs05', 'nome' => 'Spurs 2004-05', 'ano' => 2005, 'jogadores' => [
            ['nome' => 'Tony Parker',   'pos' => ['PG'],       'ovr' => 83],
            ['nome' => 'Ginobili',      'pos' => ['SG', 'SF'], 'ovr' => 87],
            ['nome' => 'Bruce Bowen',   'pos' => ['SF'],       'ovr' => 77],
            ['nome' => 'Duncan',        'pos' => ['PF', 'C'],  'ovr' => 97],
            ['nome' => 'Nesterovic',    'pos' => ['C'],        'ovr' => 76],
        ]],
        ['id' => 'spurs99', 'nome' => 'Spurs 1998-99', 'ano' => 1999, 'jogadores' => [
            ['nome' => 'Avery Johnson', 'pos' => ['PG'],       'ovr' => 78],
            ['nome' => 'Mario Elie',    'pos' => ['SG', 'SF'], 'ovr' => 76],
            ['nome' => 'Sean Elliott',  'pos' => ['SF'],       'ovr' => 82],
            ['nome' => 'Duncan',        'pos' => ['PF', 'C'],  'ovr' => 91],
            ['nome' => 'David Robinson','pos' => ['C'],        'ovr' => 90],
        ]],
        ['id' => 'sixers01', 'nome' => '76ers 2000-01', 'ano' => 2001, 'jogadores' => [
            ['nome' => 'Iverson',       'pos' => ['PG', 'SG'], 'ovr' => 95],
            ['nome' => 'Aaron McKie',   'pos' => ['SG', 'SF'], 'ovr' => 78],
            ['nome' => 'Tyrone Hill',   'pos' => ['PF'],       'ovr' => 74],
            ['nome' => 'George Lynch',  'pos' => ['SF', 'PF'], 'ovr' => 75],
            ['nome' => 'Mutombo',       'pos' => ['C'],        'ovr' => 84],
        ]],
        ['id' => 'suns93', 'nome' => 'Suns 1992-93', 'ano' => 1993, 'jogadores' => [
            ['nome' => 'Kevin Johnson', 'pos' => ['PG'],       'ovr' => 88],
            ['nome' => 'Dan Majerle',   'pos' => ['SG', 'SF'], 'ovr' => 83],
            ['nome' => 'Ceballos',      'pos' => ['SF'],       'ovr' => 80],
            ['nome' => 'Tom Chambers',  'pos' => ['PF'],       'ovr' => 81],
            ['nome' => 'Barkley',       'pos' => ['PF', 'C'],  'ovr' => 96],
        ]],
        ['id' => 'jazz97', 'nome' => 'Jazz 1996-97', 'ano' => 1997, 'jogadores' => [
            ['nome' => 'Stockton',      'pos' => ['PG'],       'ovr' => 92],
            ['nome' => 'Hornacek',      'pos' => ['SG'],       'ovr' => 84],
            ['nome' => 'Bryon Russell', 'pos' => ['SF'],       'ovr' => 76],
            ['nome' => 'Karl Malone',   'pos' => ['PF'],       'ovr' => 96],
            ['nome' => 'Ostertag',      'pos' => ['C'],        'ovr' => 74],
        ]],
        ['id' => 'jazz98', 'nome' => 'Jazz 1997-98', 'ano' => 1998, 'jogadores' => [
            ['nome' => 'Stockton',      'pos' => ['PG'],       'ovr' => 91],
            ['nome' => 'Hornacek',      'pos' => ['SG'],       'ovr' => 83],
            ['nome' => 'Bryon Russell', 'pos' => ['SF'],       'ovr' => 77],
            ['nome' => 'Karl Malone',   'pos' => ['PF'],       'ovr' => 97],
            ['nome' => 'Ostertag',      'pos' => ['C'],        'ovr' => 74],
        ]],
        ['id' => 'blazers77', 'nome' => 'Trail Blazers 1976-77', 'ano' => 1977, 'jogadores' => [
            ['nome' => 'Lionel Hollins','pos' => ['PG'],       'ovr' => 80],
            ['nome' => 'Twardzik',      'pos' => ['SG', 'PG'], 'ovr' => 76],
            ['nome' => 'Bob Gross',     'pos' => ['SF'],       'ovr' => 78],
            ['nome' => 'Maurice Lucas', 'pos' => ['PF'],       'ovr' => 85],
            ['nome' => 'Bill Walton',   'pos' => ['C'],        'ovr' => 91],
        ]],
        ['id' => 'sonics79', 'nome' => 'SuperSonics 1978-79', 'ano' => 1979, 'jogadores' => [
            ['nome' => 'Gus Williams',  'pos' => ['PG'],       'ovr' => 84],
            ['nome' => 'D. Johnson',    'pos' => ['SG', 'PG'], 'ovr' => 85],
            ['nome' => 'John Johnson',  'pos' => ['SF'],       'ovr' => 79],
            ['nome' => 'Lonnie Shelton','pos' => ['PF'],       'ovr' => 77],
            ['nome' => 'Jack Sikma',    'pos' => ['C', 'PF'],  'ovr' => 83],
        ]],
        ['id' => 'bullets71', 'nome' => 'Bullets 1970-71', 'ano' => 1971, 'jogadores' => [
            ['nome' => 'Earl Monroe',   'pos' => ['SG', 'PG'], 'ovr' => 89],
            ['nome' => 'Kevin Loughery','pos' => ['SG', 'PG'], 'ovr' => 79],
            ['nome' => 'Jack Marin',    'pos' => ['SF', 'PF'], 'ovr' => 79],
            ['nome' => 'Gus Johnson',   'pos' => ['PF'],       'ovr' => 84],
            ['nome' => 'Wes Unseld',    'pos' => ['C', 'PF'],  'ovr' => 87],
        ]],
        ['id' => 'pacers73', 'nome' => 'Pacers 1972-73 (ABA)', 'ano' => 1973, 'jogadores' => [
            ['nome' => 'Freddie Lewis', 'pos' => ['PG'],       'ovr' => 80],
            ['nome' => 'Billy Keller',  'pos' => ['SG'],       'ovr' => 75],
            ['nome' => 'Roger Brown',   'pos' => ['SF'],       'ovr' => 85],
            ['nome' => 'McGinnis',      'pos' => ['PF'],       'ovr' => 88],
            ['nome' => 'Mel Daniels',   'pos' => ['C'],        'ovr' => 86],
        ]],
        ['id' => 'nets74', 'nome' => 'Nets 1973-74 (ABA)', 'ano' => 1974, 'jogadores' => [
            ['nome' => 'Melchionni',    'pos' => ['PG'],       'ovr' => 78],
            ['nome' => 'Brian Taylor',  'pos' => ['SG'],       'ovr' => 74],
            ['nome' => 'Williamson',    'pos' => ['SG', 'SF'], 'ovr' => 77],
            // Sem pivô: os cinco nomes desta escalação são armadores e alas. Na
            // roleta isso não atrapalha (cada giro rende UM jogador, e o sorteio
            // só oferece times que tenham alguém elegível pra uma vaga aberta).
            ['nome' => 'Larry Kenon',   'pos' => ['PF', 'SF'], 'ovr' => 82],
            ['nome' => 'Julius Erving', 'pos' => ['SF'],       'ovr' => 93],
        ]],
        ['id' => 'cavs07', 'nome' => 'Cavaliers 2006-07', 'ano' => 2007, 'jogadores' => [
            ['nome' => 'Eric Snow',     'pos' => ['PG'],       'ovr' => 74],
            ['nome' => 'Larry Hughes',  'pos' => ['SG'],       'ovr' => 79],
            ['nome' => 'LeBron',        'pos' => ['SF', 'PF'], 'ovr' => 93],
            ['nome' => 'Drew Gooden',   'pos' => ['PF'],       'ovr' => 78],
            ['nome' => 'Ilgauskas',     'pos' => ['C'],        'ovr' => 80],
        ]],
        ['id' => 'cavs18', 'nome' => 'Cavaliers 2017-18', 'ano' => 2018, 'jogadores' => [
            ['nome' => 'Korver',        'pos' => ['PG', 'SG'], 'ovr' => 76],
            ['nome' => 'J.R. Smith',    'pos' => ['SG', 'SF'], 'ovr' => 77],
            ['nome' => 'LeBron',        'pos' => ['SF', 'PF'], 'ovr' => 97],
            ['nome' => 'Love',          'pos' => ['PF', 'C'],  'ovr' => 86],
            ['nome' => 'T. Thompson',   'pos' => ['C', 'PF'],  'ovr' => 78],
        ]],
        ['id' => 'magic95', 'nome' => 'Magic 1994-95', 'ano' => 1995, 'jogadores' => [
            ['nome' => 'Penny',         'pos' => ['PG', 'SG'], 'ovr' => 90],
            ['nome' => 'Nick Anderson', 'pos' => ['SG', 'SF'], 'ovr' => 80],
            ['nome' => 'Dennis Scott',  'pos' => ['SF'],       'ovr' => 78],
            ['nome' => 'Horace Grant',  'pos' => ['PF'],       'ovr' => 84],
            ['nome' => 'Shaq',          'pos' => ['C'],        'ovr' => 93],
        ]],
        ['id' => 'kings02', 'nome' => 'Kings 2001-02', 'ano' => 2002, 'jogadores' => [
            ['nome' => 'Mike Bibby',    'pos' => ['PG'],       'ovr' => 84],
            ['nome' => 'Doug Christie', 'pos' => ['SG'],       'ovr' => 79],
            ['nome' => 'Peja',          'pos' => ['SF'],       'ovr' => 86],
            ['nome' => 'Chris Webber',  'pos' => ['PF'],       'ovr' => 91],
            ['nome' => 'Vlade Divac',   'pos' => ['C'],        'ovr' => 82],
        ]],
        ['id' => 'jazz08', 'nome' => 'Jazz 2007-08', 'ano' => 2008, 'jogadores' => [
            ['nome' => 'Deron Williams','pos' => ['PG'],       'ovr' => 88],
            ['nome' => 'Ronnie Brewer', 'pos' => ['SG'],       'ovr' => 76],
            ['nome' => 'Kirilenko',     'pos' => ['SF', 'PF'], 'ovr' => 83],
            ['nome' => 'Carlos Boozer', 'pos' => ['PF'],       'ovr' => 86],
            ['nome' => 'Okur',          'pos' => ['C', 'PF'],  'ovr' => 80],
        ]],
        ['id' => 'nuggets09', 'nome' => 'Nuggets 2008-09', 'ano' => 2009, 'jogadores' => [
            ['nome' => 'Billups',       'pos' => ['PG'],       'ovr' => 86],
            ['nome' => 'J.R. Smith',    'pos' => ['SG'],       'ovr' => 78],
            ['nome' => 'Carmelo',       'pos' => ['SF', 'PF'], 'ovr' => 91],
            ['nome' => 'Kenyon Martin', 'pos' => ['PF'],       'ovr' => 80],
            ['nome' => 'Nene',          'pos' => ['C'],        'ovr' => 79],
        ]],
        ['id' => 'grizzlies13', 'nome' => 'Grizzlies 2012-13', 'ano' => 2013, 'jogadores' => [
            ['nome' => 'Mike Conley',   'pos' => ['PG'],       'ovr' => 84],
            ['nome' => 'Tony Allen',    'pos' => ['SG'],       'ovr' => 78],
            ['nome' => 'Rudy Gay',      'pos' => ['SF', 'PF'], 'ovr' => 82],
            ['nome' => 'Zach Randolph', 'pos' => ['PF'],       'ovr' => 86],
            ['nome' => 'Marc Gasol',    'pos' => ['C'],        'ovr' => 88],
        ]],
        ['id' => 'thunder12', 'nome' => 'Thunder 2011-12', 'ano' => 2012, 'jogadores' => [
            ['nome' => 'Westbrook',     'pos' => ['PG'],       'ovr' => 91],
            ['nome' => 'Sefolosha',     'pos' => ['SG'],       'ovr' => 75],
            ['nome' => 'Durant',        'pos' => ['SF', 'PF'], 'ovr' => 95],
            ['nome' => 'Serge Ibaka',   'pos' => ['PF'],       'ovr' => 81],
            ['nome' => 'Perkins',       'pos' => ['C'],        'ovr' => 76],
        ]],
        ['id' => 'knicks99', 'nome' => 'Knicks 1998-99', 'ano' => 1999, 'jogadores' => [
            ['nome' => 'Charlie Ward',  'pos' => ['PG'],       'ovr' => 74],
            ['nome' => 'Allan Houston', 'pos' => ['SG'],       'ovr' => 84],
            ['nome' => 'Sprewell',      'pos' => ['SF', 'SG'], 'ovr' => 86],
            ['nome' => 'Larry Johnson', 'pos' => ['PF'],       'ovr' => 80],
            ['nome' => 'Ewing',         'pos' => ['C'],        'ovr' => 84],
        ]],
        ['id' => 'rockets18', 'nome' => 'Rockets 2017-18', 'ano' => 2018, 'jogadores' => [
            ['nome' => 'Chris Paul',    'pos' => ['PG'],       'ovr' => 92],
            ['nome' => 'Harden',        'pos' => ['SG'],       'ovr' => 96],
            ['nome' => 'Trevor Ariza',  'pos' => ['SF'],       'ovr' => 78],
            ['nome' => 'P.J. Tucker',   'pos' => ['PF'],       'ovr' => 76],
            ['nome' => 'Capela',        'pos' => ['C'],        'ovr' => 82],
        ]],
        ['id' => 'nuggets95', 'nome' => 'Nuggets 1994-95', 'ano' => 1995, 'jogadores' => [
            ['nome' => 'Robert Pack',   'pos' => ['PG'],       'ovr' => 76],
            ['nome' => 'Abdul-Rauf',    'pos' => ['PG', 'SG'], 'ovr' => 80],
            ['nome' => 'Bryant Stith',  'pos' => ['SG', 'SF'], 'ovr' => 76],
            ['nome' => 'LaPhonso Ellis','pos' => ['PF'],       'ovr' => 78],
            ['nome' => 'Mutombo',       'pos' => ['C'],        'ovr' => 86],
        ]],
        ['id' => 'warriors07', 'nome' => 'Warriors 2006-07', 'ano' => 2007, 'jogadores' => [
            ['nome' => 'Baron Davis',   'pos' => ['PG'],       'ovr' => 87],
            ['nome' => 'J. Richardson', 'pos' => ['SG', 'SF'], 'ovr' => 82],
            ['nome' => 'S. Jackson',    'pos' => ['SF', 'SG'], 'ovr' => 80],
            ['nome' => 'Al Harrington', 'pos' => ['PF'],       'ovr' => 79],
            ['nome' => 'Biedrins',      'pos' => ['C'],        'ovr' => 74],
        ]],
        ['id' => 'suns05', 'nome' => 'Suns 2004-05', 'ano' => 2005, 'jogadores' => [
            ['nome' => 'Steve Nash',    'pos' => ['PG'],       'ovr' => 92],
            ['nome' => 'Joe Johnson',   'pos' => ['SG', 'SF'], 'ovr' => 84],
            ['nome' => 'Shawn Marion',  'pos' => ['SF', 'PF'], 'ovr' => 87],
            ['nome' => 'Stoudemire',    'pos' => ['PF', 'C'],  'ovr' => 88],
            ['nome' => 'Q. Richardson', 'pos' => ['SF'],       'ovr' => 78],
        ]],
        ['id' => 'blazers00', 'nome' => 'Trail Blazers 1999-00', 'ano' => 2000, 'jogadores' => [
            ['nome' => 'Stoudamire',    'pos' => ['PG'],       'ovr' => 78],
            ['nome' => 'Steve Smith',   'pos' => ['SG'],       'ovr' => 80],
            ['nome' => 'Pippen',        'pos' => ['SF', 'PF'], 'ovr' => 86],
            ['nome' => 'R. Wallace',    'pos' => ['PF'],       'ovr' => 85],
            ['nome' => 'Sabonis',       'pos' => ['C'],        'ovr' => 82],
        ]],
        ['id' => 'lakers06', 'nome' => 'Lakers 2005-06', 'ano' => 2006, 'jogadores' => [
            ['nome' => 'Smush Parker',  'pos' => ['PG'],       'ovr' => 71],
            ['nome' => 'Kobe',          'pos' => ['SG', 'SF'], 'ovr' => 95],
            ['nome' => 'Devean George', 'pos' => ['SF'],       'ovr' => 70],
            ['nome' => 'Lamar Odom',    'pos' => ['PF', 'SF'], 'ovr' => 84],
            ['nome' => 'Kwame Brown',   'pos' => ['C'],        'ovr' => 72],
        ]],
        ['id' => 'nets02', 'nome' => 'Nets 2001-02', 'ano' => 2002, 'jogadores' => [
            ['nome' => 'Jason Kidd',    'pos' => ['PG'],       'ovr' => 90],
            ['nome' => 'Kerry Kittles', 'pos' => ['SG'],       'ovr' => 79],
            ['nome' => 'Kenyon Martin', 'pos' => ['PF', 'SF'], 'ovr' => 82],
            ['nome' => 'Van Horn',      'pos' => ['PF'],       'ovr' => 80],
            ['nome' => 'MacCulloch',    'pos' => ['C'],        'ovr' => 74],
        ]],
        ['id' => 'bucks01', 'nome' => 'Bucks 2000-01', 'ano' => 2001, 'jogadores' => [
            ['nome' => 'Sam Cassell',   'pos' => ['PG'],       'ovr' => 84],
            ['nome' => 'Ray Allen',     'pos' => ['SG'],       'ovr' => 88],
            ['nome' => 'Glenn Robinson','pos' => ['SF'],       'ovr' => 84],
            ['nome' => 'Tim Thomas',    'pos' => ['PF'],       'ovr' => 78],
            ['nome' => 'Scott Williams','pos' => ['C'],        'ovr' => 70],
        ]],
        ['id' => 'wizards79', 'nome' => 'Bullets 1978-79', 'ano' => 1979, 'jogadores' => [
            ['nome' => 'Tom Henderson', 'pos' => ['PG'],       'ovr' => 78],
            ['nome' => 'Kevin Grevey',  'pos' => ['SG'],       'ovr' => 80],
            ['nome' => 'Dandridge',     'pos' => ['SF', 'PF'], 'ovr' => 86],
            ['nome' => 'Elvin Hayes',   'pos' => ['PF', 'C'],  'ovr' => 87],
            ['nome' => 'Wes Unseld',    'pos' => ['C'],        'ovr' => 86],
        ]],
        ['id' => 'cavs89', 'nome' => 'Cavaliers 1988-89', 'ano' => 1989, 'jogadores' => [
            ['nome' => 'Mark Price',    'pos' => ['PG'],       'ovr' => 84],
            ['nome' => 'Ron Harper',    'pos' => ['SG', 'SF'], 'ovr' => 82],
            ['nome' => 'Larry Nance',   'pos' => ['PF', 'C'],  'ovr' => 84],
            ['nome' => 'Daugherty',     'pos' => ['C'],        'ovr' => 84],
            ['nome' => 'Hot Rod',       'pos' => ['PF'],       'ovr' => 78],
        ]],
        ['id' => 'pacers00', 'nome' => 'Pacers 1999-00', 'ano' => 2000, 'jogadores' => [
            ['nome' => 'Mark Jackson',  'pos' => ['PG'],       'ovr' => 80],
            ['nome' => 'Reggie Miller', 'pos' => ['SG'],       'ovr' => 88],
            ['nome' => 'Jalen Rose',    'pos' => ['SF', 'SG'], 'ovr' => 83],
            ['nome' => 'Dale Davis',    'pos' => ['PF'],       'ovr' => 78],
            ['nome' => 'Rik Smits',     'pos' => ['C'],        'ovr' => 80],
        ]],
        ['id' => 'bulls89', 'nome' => 'Bulls 1988-89', 'ano' => 1989, 'jogadores' => [
            ['nome' => 'Sam Vincent',   'pos' => ['PG'],       'ovr' => 74],
            ['nome' => 'Jordan',        'pos' => ['SG', 'SF'], 'ovr' => 96],
            ['nome' => 'Pippen',        'pos' => ['SF', 'PF'], 'ovr' => 82],
            ['nome' => 'Horace Grant',  'pos' => ['PF'],       'ovr' => 76],
            ['nome' => 'Dave Corzine',  'pos' => ['C'],        'ovr' => 68],
        ]],
        ['id' => 'rockets86', 'nome' => 'Rockets 1985-86', 'ano' => 1986, 'jogadores' => [
            ['nome' => 'John Lucas',    'pos' => ['PG'],       'ovr' => 78],
            ['nome' => 'Robert Reid',   'pos' => ['SG', 'SF'], 'ovr' => 77],
            ['nome' => 'Rodney McCray', 'pos' => ['SF', 'PF'], 'ovr' => 79],
            ['nome' => 'Ralph Sampson', 'pos' => ['PF', 'C'],  'ovr' => 85],
            ['nome' => 'Hakeem',        'pos' => ['C'],        'ovr' => 88],
        ]],
        ['id' => 'sonics96', 'nome' => 'SuperSonics 1995-96', 'ano' => 1996, 'jogadores' => [
            ['nome' => 'Gary Payton',   'pos' => ['PG'],       'ovr' => 90],
            ['nome' => 'Hersey Hawkins','pos' => ['SG'],       'ovr' => 79],
            ['nome' => 'Schrempf',      'pos' => ['SF', 'PF'], 'ovr' => 84],
            ['nome' => 'Shawn Kemp',    'pos' => ['PF', 'C'],  'ovr' => 91],
            ['nome' => 'Sam Perkins',   'pos' => ['C', 'PF'],  'ovr' => 78],
        ]],
        ['id' => 'nuggets13', 'nome' => 'Nuggets 2012-13', 'ano' => 2013, 'jogadores' => [
            ['nome' => 'Ty Lawson',     'pos' => ['PG'],       'ovr' => 83],
            ['nome' => 'Iguodala',      'pos' => ['SG', 'SF'], 'ovr' => 85],
            ['nome' => 'Gallinari',     'pos' => ['SF', 'PF'], 'ovr' => 80],
            ['nome' => 'Faried',        'pos' => ['PF'],       'ovr' => 78],
            ['nome' => 'JaVale McGee',  'pos' => ['C'],        'ovr' => 76],
        ]],
        ['id' => 'jazz99', 'nome' => 'Jazz 1998-99', 'ano' => 1999, 'jogadores' => [
            ['nome' => 'Stockton',      'pos' => ['PG'],       'ovr' => 88],
            ['nome' => 'Hornacek',      'pos' => ['SG'],       'ovr' => 80],
            ['nome' => 'Bryon Russell', 'pos' => ['SF'],       'ovr' => 76],
            ['nome' => 'Karl Malone',   'pos' => ['PF'],       'ovr' => 94],
            ['nome' => 'Ostertag',      'pos' => ['C'],        'ovr' => 72],
        ]],
        ['id' => 'pistons06', 'nome' => 'Pistons 2005-06', 'ano' => 2006, 'jogadores' => [
            ['nome' => 'Billups',       'pos' => ['PG'],       'ovr' => 87],
            ['nome' => 'Rip Hamilton',  'pos' => ['SG'],       'ovr' => 86],
            ['nome' => 'Tayshaun',      'pos' => ['SF'],       'ovr' => 81],
            ['nome' => 'R. Wallace',    'pos' => ['PF', 'C'],  'ovr' => 84],
            ['nome' => 'Ben Wallace',   'pos' => ['C', 'PF'],  'ovr' => 85],
        ]],
        ['id' => 'raptors16', 'nome' => 'Raptors 2015-16', 'ano' => 2016, 'jogadores' => [
            ['nome' => 'Kyle Lowry',    'pos' => ['PG'],       'ovr' => 87],
            ['nome' => 'DeRozan',       'pos' => ['SG'],       'ovr' => 85],
            ['nome' => 'DeMarre Carroll','pos' => ['SF'],      'ovr' => 76],
            ['nome' => 'Luis Scola',    'pos' => ['PF'],       'ovr' => 74],
            ['nome' => 'Valanciunas',   'pos' => ['C'],        'ovr' => 77],
        ]],
    ];
}

/** As 5 posições de um roster, na ordem em que aparecem na tela. */
function dtPosicoes(): array
{
    return ['PG', 'SG', 'SF', 'PF', 'C'];
}
